name: Vulncheck

on:
  schedule:
  - cron: '0 10 */14 * *'
jobs:
  vuln:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
    - uses: golang/govulncheck-action@31f7c5463448f83528bd771c2d978d940080c9fd # v1.0.4-1
