name: Vulncheck

on:
  schedule:
  - cron: '0 10 */14 * *'
jobs:
  vuln:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
    - uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
